export const cardMeta = [
  {
    id: "card-0001",
    title: "청년 지원금",
    type: "policy",
    description: "서울시 청년 대상 최대 100만원 지원 정책",
    location: "서울",
    category: "취업",
    age: "20대",
    status: "미취업",
    bgImage: "/img/CardImage/Policy/1.jpeg",
  },
  {
    id: "card-0002",
    title: "청년 월세 지원",
    type: "policy",
    description: "청년 주거 안정을 위한 월세 지원 정책",
    location: "부산",
    category: "주거",
    age: "20대",
    status: "재직",
    bgImage: "/img/CardImage/Policy/2.jpeg",
  },
  {
    id: "card-0003",
    title: "청년 월세 지원",
    type: "policy",
    description: "청년 주거 안정을 위한 월세 지원 정책",
    location: "부산",
    category: "주거",
    age: "20대",
    status: "재직",
    bgImage: "/img/CardImage/Policy/3.jpeg",
  },
  {
    id: "card-0004",
    title: "청년 월세 지원",
    type: "policy",
    description: "청년 주거 안정을 위한 월세 지원 정책",
    location: "부산",
    category: "주거",
    age: "20대",
    status: "재직",
    bgImage: "/img/CardImage/Policy/4.jpeg",
  },
  {
    id: "card-0005",
    title: "청년 월세 지원",
    type: "policy",
    description: "청년 주거 안정을 위한 월세 지원 정책",
    location: "부산",
    category: "주거",
    age: "20대",
    status: "재직",
    bgImage: "/img/CardImage/Policy/5.jpeg",
  },
  {
    id: "card-0006",
    title: "청년 월세 지원",
    type: "policy",
    description: "청년 주거 안정을 위한 월세 지원 정책",
    location: "부산",
    category: "주거",
    age: "20대",
    status: "재직",
    bgImage: "/img/CardImage/Policy/6.jpeg",
  },
  {
    id: "card-0007",
    title: "청년 월세 지원",
    type: "policy",
    description: "청년 주거 안정을 위한 월세 지원 정책",
    location: "부산",
    category: "주거",
    age: "20대",
    status: "재직",
    bgImage: "/img/CardImage/Policy/7.jpeg",
  },
  {
    id: "card-0008",
    title: "청년 월세 지원",
    type: "policy",
    description: "청년 주거 안정을 위한 월세 지원 정책",
    location: "부산",
    category: "주거",
    age: "20대",
    status: "재직",
    bgImage: "/img/CardImage/Policy/8.jpeg",
  },
];
