export const cardMeta = [
  {
    id: "card-0001",
    title: "청년 주거 지원",
    type: "policy",
    description: "서울시 청년 대상 최대 100만원 지원 정책",
    location: ["서울특별시"],
    category: ["주거"],
    age: ["25~29"],
    status: ["구직자"],
    bgImage: "/img/CardImage/Policy/1.jpeg",
  },
  {
    id: "card-0002",
    title: "청년 월세 지원",
    type: "policy",
    description: "청년 주거 안정을 위한 월세 지원 정책",
    location: ["서울특별시", "경기도"],
    category: ["문화/예술"],
    age: "25~29",
    status: ["재직"],
    bgImage: "/img/CardImage/Policy/2.jpeg",
  },
  {
    id: "card-0003",
    title: "청년 교육 지원",
    type: "policy",
    description: "부산 지역 청년 교육 지원 프로그램",
    location: "강원도",
    category: ["문화/예술"],
    age: ["25~29"],
    status: ["구직자", "재직자"],
    bgImage: "/img/CardImage/Policy/3.jpeg",
  },
  {
    id: "card-0004",
    title: "청년 취업 지원",
    type: "policy",
    description: "청년 취업 촉진을 위한 정책",
    location: ["서울특별시", "경기도", "충청도", "경상도"],
    category: ["교육", "일자리", "생활지원"],
    age: ["25~29", "30~34", "35~39"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/4.jpeg",
  },
  {
    id: "card-0005",
    title: "청년 문화예술 지원",
    type: "policy",
    description: "부산 지역 청년 문화예술 지원 정책",
    location: ["서울특별시", "경기도", "전라도"],
    category: ["주거", "문화/예술", "생활지원"],
    age: ["19~24", "25~29", "30~34"],
    status: ["구직자", "학생"],
    bgImage: "/img/CardImage/Policy/5.jpeg",
  },
  {
    id: "card-0006",
    title: "청년 생활 지원",
    type: "policy",
    description: "청년 생활 안정 지원 정책",
    location: ["강원도", "충청도", "경기도"],
    category: ["주거", "문화/예술"],
    age: ["25~29"],
    status: ["미취업", "학생"],
    bgImage: "/img/CardImage/Policy/6.jpeg",
  },
  {
    id: "card-0007",
    title: "청년 주거 지원",
    type: "policy",
    description: "서울시 청년 주거 안정 지원",
    location: "서울특별시",
    category: ["주거", "일자리", "교육"],
    age: "30~34",
    status: ["재직자", "학생"],
    bgImage: "/img/CardImage/Policy/7.jpeg",
  },
  {
    id: "card-0008",
    title: "청년 복지 지원",
    type: "policy",
    description: "부산 청년을 위한 복지 지원 정책",
    location: "서울특별시",
    category: "주거",
    age: ["19~24"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/8.jpeg",
  },
];
