export const cardMeta = [
  {
    id: "card-0001",
    title: "[금융위원회] 서민금융 종합플랫폼 잇다",
    type: "finance",
    bank: "정보 한 입",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/1.jpeg",
  },
  {
    id: "card-0002",
    title: "청년도약계좌 기여금 확대",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원"],
    bgImage: "/img/CardImage/Finance/2.jpeg",
  },
  {
    id: "card-0003",
    title: "[금융위원회] 금융지주회사법·시행령 개정안 입법예고",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/3.jpeg",
  },
  {
    id: "card-0004",
    title: "[서민금융진흥원] 온라인 금융교육 이벤트",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/4.jpeg",
  },
  {
    id: "card-0005",
    title: "[서민금융진흥원] 포용이의 홀로서기",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/5.jpeg",
  },
  {
    id: "card-0006",
    title: "[금융지식] 연체가 뭘 의미하는 줄 알아?",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/6.jpeg",
  },
  {
    id: "card-0007",
    title: "[청년행복] 활동비 최대 200만원 지원! 서울 동아리 ON",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/7.jpeg",
  },
  {
    id: "card-0008",
    title: "[금융위원회] 온라인 예금중개 서비스 도입",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/8.jpeg",
  },
  {
    id: "card-0009",
    title: "[서민금융생활상담] 꼭 알아야 할 금융소비자보호법",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/9.jpeg",
  },
  {
    id: "card-0010",
    title: "[서민금융진흥원] 금융지식 형성을 위한 온택트 공개교육",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/10.jpeg",
  },
  {
    id: "card-0011",
    title: "[국민은행] 적금도 DIY시대! 내맘대로 적금",
    type: "finance",
    bank: "국민",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/11.jpeg",
  },
  {
    id: "card-0012",
    title: "[알고가는 금융지식] 뱅크어슈어런스란?",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/12.jpeg",
  },
  {
    id: "card-0013",
    title: "[국민은행] 알고가야하는 금 투자 방법",
    type: "finance",
    bank: "국민",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/13.jpeg",
  },
  {
    id: "card-0014",
    title: "[국민은행 X 노랑풍선] 두근두근 여행적금",
    type: "finance",
    bank: "국민",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월"],
    amount: ["만원 미만", "1만원 ~ 30만원", "30만원 ~ 50만원"],
    bgImage: "/img/CardImage/Finance/14.jpeg",
  },
  {
    id: "card-0015",
    title: "[국민은행] KB TWO테크 외화정기예금",
    type: "finance",
    bank: "국민",
    rate: "기본 금리",
    period: ["3개월", "6개월", "1년"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/15.jpeg",
  },
  {
    id: "card-0016",
    title: "[알고가는 금융지식] 외화통장으로 환테크 하는 법",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/16.jpeg",
  },
  {
    id: "card-0017",
    title: "[금융톡] 매월 올리는 내통장 금리",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/17.jpeg",
  },
  {
    id: "card-0018",
    title: "[국민은행] 더 높이, 더 멀리! 「KB청년도약플러스적금」",
    type: "finance",
    bank: "국민",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
    ],
    bgImage: "/img/CardImage/Finance/18.jpeg",
  },
  {
    id: "card-0019",
    title: "[국민은행] 장병내일준비적금",
    type: "finance",
    bank: "국민",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/19.jpeg",
  },
  {
    id: "card-0020",
    title: '[국민은행] 우대혜택에 기부 챌린지까지! "KB맑은하늘 적금"',
    type: "finance",
    bank: "국민",
    rate: ["기본 금리", "최고 금리"],
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: ["만원 미만", "1만원 ~ 30만원"],
    bgImage: "/img/CardImage/Finance/20.jpeg",
  },
  {
    id: "card-0021",
    title: "[국민은행] 특★한 적금",
    type: "finance",
    bank: "국민",
    rate: "최고 금리",
    period: ["1년", "1년 이상"],
    amount: ["50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/21.jpeg",
  },
  {
    id: "card-0022",
    title: "[국민은행 X 모니모] 차곡차곡! 모니머니!",
    type: "finance",
    bank: "국민",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/22.jpeg",
  },
  {
    id: "card-0023",
    title: "[국민은행] 올인원급여통장 가입하고 보너스 월급 받아가세요!",
    type: "finance",
    bank: "국민",
    rate: "최고 금리",
    period: ["6개월", "1년", "1년 이상"],
    amount: ["50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/23.jpeg",
  },
  {
    id: "card-0024",
    title: "[국민은행] 금융도 내 스타일에 맞추는 KB 마이핏",
    type: "finance",
    bank: "국민",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/24.jpeg",
  },
  {
    id: "card-0025",
    title: "[국민은행] 군 생활 필수카드, 나라사랑카드",
    type: "finance",
    bank: "국민",
    rate: "최고 금리",
    period: ["1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/25.jpeg",
  },
  {
    id: "card-0026",
    title: "[토스뱅크] 귀여운데 그렇지만도 않다? 「키워봐요 적금",
    type: "finance",
    bank: "토스",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/26.jpeg",
  },
  {
    id: "card-0027",
    title: "[토스뱅크] 절약왕 굴비와 함께 알뜰하게 아껴봐",
    type: "finance",
    bank: "토스",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/27.jpeg",
  },
  {
    id: "card-0028",
    title: "[토스뱅크] 복잡한 조건 없이 꾸준히만 하면 된다구",
    type: "finance",
    bank: "토스",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/28.jpeg",
  },
  {
    id: "card-0029",
    title: "[토스뱅크] 미래를 위한 현명한 선택, 아이서비스 출시",
    type: "finance",
    bank: "토스",
    rate: "기본 금리",
    period: "1년 이상",
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/29.jpeg",
  },
  {
    id: "card-0030",
    title: "[토스뱅크] 먼저 이자 받는 예금 출시",
    type: "finance",
    bank: "토스",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/30.jpeg",
  },
  {
    id: "card-0031",
    title: "[토스뱅크] 믿을 수 있는 전세대출! 전월세보증금대출 출시",
    type: "finance",
    bank: "토스",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/31.jpeg",
  },
  {
    id: "card-0032",
    title: "[토스뱅크] 현금이 급하게 필요할 땐, 토스뱅크 비상금 대출",
    type: "finance",
    bank: "토스",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/32.jpeg",
  },
  {
    id: "card-0033",
    title: "[토스뱅크] 햇살론 뱅크 - 가장 빠르고, 폭넓게 포용금융을 실시하다",
    type: "finance",
    bank: "토스",
    rate: "최고 금리",
    period: ["1년", "1년 이상"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/33.jpeg",
  },
  {
    id: "card-0034",
    title: "[토스뱅크] 외화통장 송금 무료 프로모션",
    type: "finance",
    bank: "토스",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/34.jpeg",
  },
  {
    id: "card-0035",
    title: "[NH농협] 비대면 전용 정기예금「NH월원e예금」출시",
    type: "finance",
    bank: "NH농협",
    rate: "기본 금리",
    period: ["6개월", "1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/35.jpeg",
  },
  {
    id: "card-0036",
    title: "[NH농협] 창립 58주년 기념, 고객사은 정기 예금",
    type: "finance",
    bank: "NH농협",
    rate: ["기본 금리", "최고 금리"],
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/36.jpeg",
  },
  {
    id: "card-0037",
    title: "[NH농협] 내가 Green 초록세상 적금",
    type: "finance",
    bank: "NH농협",
    rate: "기본 금리",
    period: ["6개월", "1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원"],
    bgImage: "/img/CardImage/Finance/37.jpeg",
  },
  {
    id: "card-0038",
    title: "[NH농협] 농협은행 신규 이벤트 - 오늘, 올뱅?",
    type: "finance",
    bank: "NH농협",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/38.jpeg",
  },
  {
    id: "card-0039",
    title: "[NH농협] 값진 봄엔 더 값진 적금으로!",
    type: "finance",
    bank: "NH농협",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월"],
    amount: ["만원 미만", "1만원 ~ 30만원", "30만원 ~ 50만원"],
    bgImage: "/img/CardImage/Finance/39.jpeg",
  },
  {
    id: "card-0040",
    title: "[NH농협] NH왈츠회전예금 II",
    type: "finance",
    bank: "NH농협",
    rate: "최고 금리",
    period: ["6개월", "1년", "1년 이상"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/40.jpeg",
  },
  {
    id: "card-0041",
    title: "[NH농협] 싱그러운 봄향기 家득, 희망 家득 이벤트",
    type: "finance",
    bank: "NH농협",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/41.jpeg",
  },
  {
    id: "card-0042",
    title: "[NH농협] NH1934 월복리 적금",
    type: "finance",
    bank: "NH농협",
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/42.jpeg",
  },
  {
    id: "card-0043",
    title: "[NH농협] 농협과 함께 2025갓생살기 가보자고!",
    type: "finance",
    bank: "NH농협",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/43.jpeg",
  },
  {
    id: "card-0044",
    title: "[알고가는 금융지식] 저소득층을 위한 햇살론뱅크",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/44.jpeg",
  },
  {
    id: "card-0045",
    title: "[금융위원회] 스마트폰으로 쉽게 갈아타는 신용대출",
    type: "finance",
    bank: "정보 한 입",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/45.jpeg",
  },
  {
    id: "card-0046",
    title: "[신한은행] 슈퍼SOL 통장! 통큰 이자!",
    type: "finance",
    bank: "신한",
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/46.jpeg",
  },
  {
    id: "card-0047",
    title: '[신한은행 X 땡겨요] 소상공인 상생을 위한 "땡겨드림 대출"',
    type: "finance",
    bank: "신한",
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/47.jpeg",
  },
  {
    id: "card-0048",
    title: "[신한은행] 현금처럼 사용하는 신한 머니쿠폰 출시!",
    type: "finance",
    bank: "신한",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/48.jpeg",
  },
  {
    id: "card-0049",
    title: "[신한은행 X 모두투어] 외화예금 4U 이벤트",
    type: "finance",
    bank: "신한",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/49.jpeg",
  },
  {
    id: "card-0050",
    title:
      "[신한은행 X 토스] 신한 토스페이 적금 - 토스페이로 결제하고 우대금리 받아가세요!",
    type: "finance",
    bank: ["신한", "토스"],
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/50.jpeg",
  },
  {
    id: "card-0051",
    title: "[신한은행] 창립 40주년 기념 특판 감사 이벤트 실시",
    type: "finance",
    bank: "신한",
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/51.jpeg",
  },
  {
    id: "card-0052",
    title: "[신한은행] 이용하면 좋은데, 처음이면 더 좋은「SOL만해 적금」",
    type: "finance",
    bank: "신한",
    rate: "기본 금리",
    period: ["6개월", "1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/52.jpeg",
  },
  {
    id: "card-0053",
    title: '[신한은행] 당신을 기다리고 있었어요! "안녕, 반가워 적금"',
    type: "finance",
    bank: "신한",
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/53.jpeg",
  },
  {
    id: "card-0054",
    title:
      '[신한은행] "청"년들의 "포"부와 "도"전을 응원합니다! - 청포도 청년적금',
    type: "finance",
    bank: "신한",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/54.jpeg",
  },
  {
    id: "card-0055",
    title: "[신한은행] 일본여행 필수템 - SOL트래블J 체크카드 이벤트",
    type: "finance",
    bank: "신한",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/55.jpeg",
  },
  {
    id: "card-0056",
    title: "[우리은행] 생성형 AI기반 AI뱅커 출시",
    type: "finance",
    bank: "우리",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/56.jpeg",
  },
  {
    id: "card-0057",
    title: "[우리은행] 올여름 LCK도 우리와 함께!",
    type: "finance",
    bank: "우리",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/57.jpeg",
  },
  {
    id: "card-0058",
    title: "[우리은행 X 네이버 파이넨셜] 스마트플레이스 대출",
    type: "finance",
    bank: "우리",
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/58.jpeg",
  },
  {
    id: "card-0059",
    title: "[우리은행] 원하는 자동차 더 쉽게 만나도록 우리 WON카",
    type: "finance",
    bank: "우리",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/59.jpeg",
  },
  {
    id: "card-0060",
    title: "[우리은행] TOK 예치하면, TOK 만기되는 TOK7 적금",
    type: "finance",
    bank: "우리",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/60.jpeg",
  },
  {
    id: "card-0061",
    title: "[우리은행] 청년의 도약을 위하여! 금리 + 도약지원금 플러스",
    type: "finance",
    bank: "우리",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/61.jpeg",
  },
  {
    id: "card-0062",
    title: "[우리은행] 건강과 금융을 지키는, 11% 데일리 워킹 적금",
    type: "finance",
    bank: "우리",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/62.jpeg",
  },
  {
    id: "card-0063",
    title:
      "[우리은행 X 네이버 파이넨셜] 스마트스토어 사장님을 위해 다 담았다구요!",
    type: "finance",
    bank: "우리",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/63.jpeg",
  },
  {
    id: "card-0064",
    title: '[우리은행] 간단해서 쉬운 "우리닷컴 적금"',
    type: "finance",
    bank: "우리",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/64.jpeg",
  },
  {
    id: "card-0065",
    title: "[우리은행] 「우월한 월급 통장」출시 기념, 완전 럭키비키자나?!",
    type: "finance",
    bank: "우리",
    rate: "최고 금리",
    period: ["6개월", "1년", "1년 이상"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/65.jpeg",
  },
  {
    id: "card-0066",
    title: "[우리은행] 지갑과 금고 서비스를 내 맘대로 - 머니클립 통장",
    type: "finance",
    bank: "우리",
    rate: "기본 금리",
    period: ["1개월", "3개월"],
    amount: ["만원 미만", "1만원 ~ 30만원"],
    bgImage: "/img/CardImage/Finance/66.jpeg",
  },
  {
    id: "card-0067",
    title: "[수협은행] 아가야 환영해!",
    type: "finance",
    bank: "수협",
    rate: "기본 금리",
    period: ["1년", "1년 이상"],
    amount: ["1만원 ~ 30만원", "30만원 ~ 50만원", "50만원 ~ 100만원"],
    bgImage: "/img/CardImage/Finance/67.jpeg",
  },
  {
    id: "card-0068",
    title: "[수협은행 X 신한카드] 최고 연 7.9% 혜택! - Hey! 친구 적금",
    type: "finance",
    bank: ["수협", "신한"],
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/68.jpeg",
  },
  {
    id: "card-0069",
    title: "[수협은행] 깨끗한 바다 만들기 좋은 수! 해양플라스틱 ZERO 법인 MMDA",
    type: "finance",
    bank: "수협",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/69.jpeg",
  },
  {
    id: "card-0070",
    title: "[수협은행] Sh플러스 알파적금(7차)",
    type: "finance",
    bank: "수협",
    rate: "최고 금리",
    period: ["6개월", "1년", "1년 이상"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/70.jpeg",
  },
  {
    id: "card-0071",
    title: "[수협은행] 수협 공동주택중도금 집단대출(HUG보증)",
    type: "finance",
    bank: "수협",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/71.jpeg",
  },
  {
    id: "card-0072",
    title:
      "[수협은행] 중도금 대출 고객의 잔금전환 우대를 위하여 - Sh으뜸모기지론",
    type: "finance",
    bank: "수협",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/72.jpeg",
  },
  {
    id: "card-0073",
    title: "[수협은행] 손끝으로 환테크를! Sh외화레인지 예금",
    type: "finance",
    bank: "수협",
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/73.jpeg",
  },
  {
    id: "card-0074",
    title: "[신한은행] 최대 20% 땡기세요! 「땡겨요 plus」",
    type: "finance",
    bank: "신한",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/74.jpeg",
  },
  {
    id: "card-0075",
    title: "[수협은행] 첫 금융, MZ를 응원해!",
    type: "finance",
    bank: "수협",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: ["만원 미만", "1만원 ~ 30만원", "30만원 ~ 50만원"],
    bgImage: "/img/CardImage/Finance/75.jpeg",
  },
  {
    id: "card-0076",
    title: "[기업은행] 총 납입액의 40% 소득공제 - 청년형 소득공제 장기펀드",
    type: "finance",
    bank: "기업",
    rate: ["기본 금리", "최고 금리"],
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/76.jpeg",
  },
  {
    id: "card-0077",
    title: "[기업은행] 기업고객을 위한 IBK의 선물, 희망 e-룸 변동금리적금",
    type: "finance",
    bank: "기업",
    rate: "최고 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/77.jpeg",
  },
  {
    id: "card-0078",
    title: "[기업은행] 기업 비대면채널 전용 i-ONE U 통장",
    type: "finance",
    bank: "기업",
    rate: "최고 금리",
    period: ["6개월", "1년", "1년 이상"],
    amount: ["30만원 ~ 50만원", "50만원 ~ 100만원", "100만원 초과"],
    bgImage: "/img/CardImage/Finance/78.jpeg",
  },
  {
    id: "card-0079",
    title: "[기업은행] 잔액 300만원까지 연 3% 금리 제공!",
    type: "finance",
    bank: "기업",
    rate: "기본 금리",
    period: ["1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/79.jpeg",
  },
  {
    id: "card-0080",
    title: "[기업은행] #IBK 상품가이드, 사업자등록 원스톱 서비스",
    type: "finance",
    bank: "기업",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/80.jpeg",
  },
  {
    id: "card-0081",
    title: "[기업은행] 심플한 우대금리 조건으로 청년도약플러스 적금을 함께",
    type: "finance",
    bank: "기업",
    rate: "기본 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/81.jpeg",
  },
  {
    id: "card-0082",
    title: "[카카오뱅크] 누구나 쉽게 이용하는 카뱅 입출금 통장",
    type: "finance",
    bank: "카카오",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/82.jpeg",
  },
  {
    id: "card-0083",
    title: "[카카오뱅크] 사랑하는 만큼, 최애적금",
    type: "finance",
    bank: "카카오",
    rate: "기본 금리",
    period: ["3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/83.jpeg",
  },
  {
    id: "card-0084",
    title: "[카카오뱅크] 카뱅 세이프 박스, 내가 원할 때 이자가 쏙",
    type: "finance",
    bank: "카카오",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/84.jpeg",
  },
  {
    id: "card-0085",
    title: "[카카오뱅크 X 카카오페이지] 26주년 적금 챌린지",
    type: "finance",
    bank: "카카오",
    rate: "최고 금리",
    period: ["1개월", "3개월"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/85.jpeg",
  },
  {
    id: "card-0086",
    title: "[카카오뱅크] 매일매일 우대금리! 한달적금",
    type: "finance",
    bank: "카카오",
    rate: "최고 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/86.jpeg",
  },
  {
    id: "card-0087",
    title: "[카카오뱅크] 60초면 끝, 비상금 대출",
    type: "finance",
    bank: "카카오",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/87.jpeg",
  },
  {
    id: "card-0088",
    title: "[카카오뱅크] 어떤 집이든, 꼭 맞는 전세대출은 여기로!",
    type: "finance",
    bank: "카카오",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/88.jpeg",
  },
  {
    id: "card-0089",
    title: "[카카오뱅크] 부담갖지 않아도 되는 카카오뱅크 저금통",
    type: "finance",
    bank: "카카오",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: ["만원 미만", "1만원 ~ 30만원", "30만원 ~ 50만원"],
    bgImage: "/img/CardImage/Finance/89.jpeg",
  },
  {
    id: "card-0090",
    title: "[카카오뱅크 X 마켓컬리] 26주적금 WITH.마켓컬리",
    type: "finance",
    bank: "카카오",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월"],
    amount: ["만원 미만", "1만원 ~ 30만원", "30만원 ~ 50만원"],
    bgImage: "/img/CardImage/Finance/90.jpeg",
  },
  {
    id: "card-0091",
    title: "[카카오뱅크] 채권 투자도 역시 카카오뱅크에서!",
    type: "finance",
    bank: "카카오",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/91.jpeg",
  },
  {
    id: "card-0092",
    title: "[카카오뱅크 X 한국투자증권] 발행어음 투자도 카뱅에서 쉽고 빠르게!",
    type: "finance",
    bank: "카카오",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/92.jpeg",
  },
  {
    id: "card-0093",
    title: "[카카오뱅크 X 신한금융투자] 카카오뱅크 주식계좌 개설 서비스",
    type: "finance",
    bank: ["신한", "카카오"],
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/93.jpeg",
  },
  {
    id: "card-0094",
    title: "[카카오뱅크] 세이프박스를 아직도 모른다고?",
    type: "finance",
    bank: "카카오",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: ["만원 미만", "1만원 ~ 30만원", "30만원 ~ 50만원"],
    bgImage: "/img/CardImage/Finance/94.jpeg",
  },
  {
    id: "card-0095",
    title: "[카카오뱅크] 카뱅 주택담보대출이 이정도라구!",
    type: "finance",
    bank: "카카오",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/95.jpeg",
  },
  {
    id: "card-0096",
    title: "[카카오뱅크] 오늘부터 카카오뱅크의 편리함을 청소년들도 함께",
    type: "finance",
    bank: "카카오",
    rate: "기본 금리",
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/96.jpeg",
  },
  {
    id: "card-0097",
    title: '[카카오뱅크] 펀드도 판매가 가능하단다? - "펀드 판매 서비스" 출시',
    type: "finance",
    bank: "카카오",
    rate: ["기본 금리", "최고 금리"],
    period: ["1개월", "3개월", "6개월", "1년", "1년 이상"],
    amount: [
      "만원 미만",
      "1만원 ~ 30만원",
      "30만원 ~ 50만원",
      "50만원 ~ 100만원",
      "100만원 초과",
    ],
    bgImage: "/img/CardImage/Finance/97.jpeg",
  },
];
