export const cardMeta = [
  {
    id: "card-0001",
    title: "[국립예술단체] 청년 교육단원 통합모집",
    type: "policy",
    location: "서울특별시",
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/1.jpeg",
  },
  {
    id: "card-0002",
    title: "자립준비청년 재보호제도",
    type: "policy",
    location: ["서울특별시", "경기도"],
    category: "주거",
    age: ["19~14", "25~29"],
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/2.jpeg",
  },
  {
    id: "card-0003",
    title: "문화가 있는 날",
    type: "policy",
    location: "강원도",
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/3.jpeg",
  },
  {
    id: "card-0004",
    title: "[중앙부처] 5분 안에 알려주는 청년정책",
    type: "policy",
    location: ["경기도", "충청도", "경상도"],
    category: ["교육", "일자리", "생활지원"],
    age: ["25~29", "30~34", "35~39"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/4.jpeg",
  },
  {
    id: "card-0005",
    title: "[서울시] 해치 콘텐츠 공모전",
    type: "policy",
    location: ["서울특별시", "경기도", "전라도"],
    category: "생활지원",
    age: ["19~24", "25~29"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/5.jpeg",
  },
  {
    id: "card-0006",
    title: "2024 청년인생설계학교",
    type: "policy",
    location: ["강원도", "충청도", "경기도"],
    category: "대외활동",
    age: ["19~24", "25~29"],
    status: ["구직자", "학생"],
    bgImage: "/img/CardImage/Policy/6.jpeg",
  },
  {
    id: "card-0007",
    title: "2025 마포 청년정책 네트워크 신규위원 모집",
    type: "policy",
    location: "서울특별시",
    category: ["주거", "교육"],
    age: "30~34",
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/7.jpeg",
  },
  {
    id: "card-0008",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/8.jpeg",
  },
  {
    id: "card-0009",
    title: "[CJ제일제당] 나눔냉장고",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: ["생활지원", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/9.jpeg",
  },
  {
    id: "card-0010",
    title: "신촌 청년푸드스토어 청년 창업가 모집",
    type: "policy",
    location: ["서울특별시", "경기도"],
    category: "주거",
    age: ["19~24", "25~29"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/10.jpeg",
  },
  {
    id: "card-0011",
    title: "청년 특화 취업지원 프로그램",
    type: "policy",
    location: "강원도",
    category: ["일자리", "생활지원"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/11.jpeg",
  },
  {
    id: "card-0012",
    title: "고용보험 직업훈련 생계비 대부 지원 확대",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "경상도"],
    category: ["교육", "일자리", "생활지원"],
    age: ["25~29", "30~34"],
    status: ["재직자", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/12.jpeg",
  },
  {
    id: "card-0013",
    title: "[경기복지재단] 청년전용 버팀목 전세자금",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["30~34", "35~39"],
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/13.jpeg",
  },
  {
    id: "card-0014",
    title: "보금자리론 I",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: ["주거", "교육"],
    age: ["25~29", "30~34"],
    status: "재직자",
    bgImage: "/img/CardImage/Policy/14.jpeg",
  },
  {
    id: "card-0015",
    title: "[근로복지공단] 예술인 고용보험에 대해 알아보자",
    type: "policy",
    location: "서울특별시",
    category: ["문화/예술", "교육"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/15.jpeg",
  },
  {
    id: "card-0016",
    title: "[광주문화재단] 2025 예술활동준비금 지원사업 신청",
    type: "policy",
    location: "전라도",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: "재직자",
    bgImage: "/img/CardImage/Policy/16.jpeg",
  },
  {
    id: "card-0017",
    title: "괜찮아요, 회사 걱정은 이제 그만!",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: "교육",
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/17.jpeg",
  },
  {
    id: "card-0018",
    title: "채무조정제도의 이해",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: ["일자리", "주거", "교육", "생활지원", "대외활동", "문화/예술"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/18.jpeg",
  },
  {
    id: "card-0019",
    title: "[울산광역시 동구] 청년스테이지 ON",
    type: "policy",
    location: "경상도",
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29"],
    status: ["학생", "무직"],
    bgImage: "/img/CardImage/Policy/19.jpeg",
  },
  {
    id: "card-0020",
    title: "2025년 소상공인 지원사업 통합공고",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: ["일자리", "주거", "교육", "생활지원", "대외활동", "문화/예술"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/20.jpeg",
  },
  {
    id: "card-0021",
    title: "[교육부] 대학이 너무 멀다면, 걱정마세요!",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: "생활지원",
    age: ["19~24", "25~29"],
    status: "학생",
    bgImage: "/img/CardImage/Policy/21.jpeg",
  },
  {
    id: "card-0022",
    title: "[부산광역시] 청년 돌봄이음: 통합접수창구",
    type: "policy",
    location: "경상도",
    category: ["주거", "생활지원"],
    age: ["19~24", "25~29"],
    status: ["구직자", "학생"],
    bgImage: "/img/CardImage/Policy/22.jpeg",
  },
  {
    id: "card-0023",
    title: "[충청북도] 도내 미혼 청년소상공인 결혼을 위한 목돈 마련",
    type: "policy",
    location: "충청도",
    category: "생활지원",
    age: "30~34",
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/23.jpeg",
  },
  {
    id: "card-0024",
    title: "국가기술자격 시험 응시료 50% 지원",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: ["교육", "대외활동"],
    age: ["19~24", "25~29", "30~34"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/24.jpeg",
  },
  {
    id: "card-0025",
    title: "WELL - 글로벌 직무역량 강화 프로그램",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: "교육",
    age: ["19~24", "25~29", "30~34"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/25.jpeg",
  },
  {
    id: "card-0026",
    title: "CAP@ / 청년층직업지도",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: ["교육", "생활지원", "대외활동"],
    age: ["19~24", "25~29", "30~34"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/26.jpeg",
  },
  {
    id: "card-0027",
    title: "청년 고용절벽 해소 종합대책 발표",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: ["일자리", "주거", "교육", "생활지원", "대외활동", "문화/예술"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/27.jpeg",
  },
  {
    id: "card-0028",
    title: "2025년 확 달라지는 육아지원제도!",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: "생활지원",
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/28.jpeg",
  },
  {
    id: "card-0029",
    title: "2025 청년도전 지원사업",
    type: "policy",
    location: "서울특별시",
    category: ["일자리", "교육", "생활지원"],
    age: ["19~24", "25~29", "30~34"],
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/29.jpeg",
  },
  {
    id: "card-0030",
    title: "서울시 청년마음 건강 지원사업",
    type: "policy",
    location: "서울특별시",
    category: ["대외활동", "문화/예술"],
    age: ["19~24", "25~29"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/30.jpeg",
  },
];
