export const cardMeta = [
  {
    id: "card-0001",
    title: "[국립예술단체] 청년 교육단원 통합모집",
    type: "policy",
    location: ["서울특별시"],
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/1.jpeg",
  },
  {
    id: "card-0002",
    title: "자립준비청년 재보호제도",
    type: "policy",
    location: ["서울특별시", "경기도"],
    category: ["주거"],
    age: ["19~14", "25~29"],
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/2.jpeg",
  },
  {
    id: "card-0003",
    title: "문화가 있는 날",
    type: "policy",
    location: "강원도",
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/3.jpeg",
  },
  {
    id: "card-0004",
    title: "[중앙부처] 5분 안에 알려주는 청년정책",
    type: "policy",
    location: ["경기도", "충청도", "경상도"],
    category: ["교육", "일자리", "생활지원"],
    age: ["25~29", "30~34", "35~39"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/4.jpeg",
  },
  {
    id: "card-0005",
    title: "[서울시] 해치 콘텐츠 공모전",
    type: "policy",
    location: ["서울특별시", "경기도", "전라도"],
    category: "생활지원",
    age: ["19~24", "25~29"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/5.jpeg",
  },
  {
    id: "card-0006",
    title: "2024 청년인생설계학교",
    type: "policy",
    location: ["강원도", "충청도", "경기도"],
    category: "대외활동",
    age: ["19~24", "25~29"],
    status: ["미취업", "학생"],
    bgImage: "/img/CardImage/Policy/6.jpeg",
  },
  {
    id: "card-0007",
    title: "2025 마포 청년정책 네트워크 신규위원 모집",
    type: "policy",
    location: "서울특별시",
    category: ["주거", "교육"],
    age: "30~34",
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/7.jpeg",
  },
  {
    id: "card-0008",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/8.jpeg",
  },
  {
    id: "card-0009",
    title: "[CJ제일제당] 나눔냉장고",
    type: "policy",
    location: ["서울특별시", "경기도", "강원도", "충청도", "전라도", "경상도"],
    category: ["생활지원", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/9.jpeg",
  },
  {
    id: "card-0010",
    title: "신촌 청년푸드스토어 청년 창업가 모집",
    type: "policy",
    location: ["서울특별시", "경기도"],
    category: ["주거"],
    age: ["19~24", "25~29"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/10.jpeg",
  },
  {
    id: "card-0011",
    title: "청년 특화 취업지원 프로그램",
    type: "policy",
    location: "강원도",
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/11.jpeg",
  },
  {
    id: "card-0012",
    title: "[중앙부처] 5분 안에 알려주는 청년정책",
    type: "policy",
    location: ["경기도", "충청도", "경상도"],
    category: ["교육", "일자리", "생활지원"],
    age: ["25~29", "30~34", "35~39"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/12.jpeg",
  },
  {
    id: "card-0013",
    title: "[서울시] 해치 콘텐츠 공모전",
    type: "policy",
    location: ["서울특별시", "경기도", "전라도"],
    category: "생활지원",
    age: ["19~24", "25~29"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/13.jpeg",
  },
  {
    id: "card-0014",
    title: "2024 청년인생설계학교",
    type: "policy",
    location: ["강원도", "충청도", "경기도"],
    category: "대외활동",
    age: ["19~24", "25~29"],
    status: ["미취업", "학생"],
    bgImage: "/img/CardImage/Policy/14.jpeg",
  },
  {
    id: "card-0015",
    title: "2025 마포 청년정책 네트워크 신규위원 모집",
    type: "policy",
    location: "서울특별시",
    category: ["주거", "교육"],
    age: "30~34",
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/15.jpeg",
  },
  {
    id: "card-0016",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/16.jpeg",
  },
  {
    id: "card-0017",
    title: "[국립예술단체] 청년 교육단원 통합모집",
    type: "policy",
    location: ["서울특별시"],
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/17.jpeg",
  },
  {
    id: "card-0018",
    title: "자립준비청년 재보호제도",
    type: "policy",
    location: ["서울특별시", "경기도"],
    category: ["주거"],
    age: ["19~14", "25~29"],
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/18.jpeg",
  },
  {
    id: "card-0019",
    title: "문화가 있는 날",
    type: "policy",
    location: "강원도",
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/19.jpeg",
  },
  {
    id: "card-0020",
    title: "[중앙부처] 5분 안에 알려주는 청년정책",
    type: "policy",
    location: ["경기도", "충청도", "경상도"],
    category: ["교육", "일자리", "생활지원"],
    age: ["25~29", "30~34", "35~39"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/20.jpeg",
  },
  {
    id: "card-0021",
    title: "[서울시] 해치 콘텐츠 공모전",
    type: "policy",
    location: ["서울특별시", "경기도", "전라도"],
    category: "생활지원",
    age: ["19~24", "25~29"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/21.jpeg",
  },
  {
    id: "card-0022",
    title: "2024 청년인생설계학교",
    type: "policy",
    location: ["강원도", "충청도", "경기도"],
    category: "대외활동",
    age: ["19~24", "25~29"],
    status: ["미취업", "학생"],
    bgImage: "/img/CardImage/Policy/22.jpeg",
  },
  {
    id: "card-0023",
    title: "2025 마포 청년정책 네트워크 신규위원 모집",
    type: "policy",
    location: "서울특별시",
    category: ["주거", "교육"],
    age: "30~34",
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/23.jpeg",
  },
  {
    id: "card-0024",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/24.jpeg",
  },
  {
    id: "card-0025",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/25.jpeg",
  },
  {
    id: "card-0026",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/26.jpeg",
  },
  {
    id: "card-0027",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/27.jpeg",
  },
  {
    id: "card-0028",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/28.jpeg",
  },
  {
    id: "card-0029",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/29.jpeg",
  },
  {
    id: "card-0030",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/30.jpeg",
  },
];
