const policyDummyData = [
  {
    title: "청년 교육단원 통합 모집",
    location: "서울특별시",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/1.jpeg",
  },
  {
    title: "마포 청년정책 네트워크 신규위원 모집",
    location: "경기도",
    분야: "대외활동",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/2.jpeg",
  },
  {
    title: "2025 마포 사진 학교",
    location: "강원도",
    분야: "문화/예술",
    취업상태: "무직",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/3.jpeg",
  },
  {
    title: "서울시 청년 인생 설계 학교",
    location: "충청도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/4.jpeg",
  },
  {
    title: "해치 콘텐츠 공모전",
    location: "전라도",
    분야: "문화/예술",
    취업상태: "구직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/5.jpeg",
  },
  {
    title: "2025 결혼검진",
    location: "경상도",
    분야: "생활지원",
    취업상태: "재직자",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/6.jpeg",
  },
  {
    title: "자립준비청년 재보호제도",
    location: "서울특별시",
    분야: "주거",
    취업상태: "구직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/7.jpeg",
  },
  {
    title: "알고가는 중앙부처 청년정책",
    location: "경기도",
    분야: "일자리",
    취업상태: "재직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/8.jpeg",
  },
  {
    title: "[CJ] 나눔 냉장고",
    location: "강원도",
    분야: "생활지원",
    취업상태: "무직",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/9.jpeg",
  },
  {
    title: "누구나 즐기는 문화가 있는 날",
    location: "충청도",
    분야: "문화/예술",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/10.jpeg",
  },
  // 11~70 - 비슷한 패턴으로 작성합니다.
  {
    title: "서울 청년 창업 지원 사업",
    location: "서울특별시",
    분야: "일자리",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/11.jpeg",
  },
  {
    title: "경기도 청년 주거 안정 프로그램",
    location: "경기도",
    분야: "주거",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/12.jpeg",
  },
  {
    title: "강원도 청년 문화예술 지원금",
    location: "강원도",
    분야: "문화/예술",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/13.jpeg",
  },
  {
    title: "충청도 청년 취업 성공 패키지",
    location: "충청도",
    분야: "일자리",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/14.jpeg",
  },
  {
    title: "전라도 청년 생활 안정 자금 지원",
    location: "전라도",
    분야: "생활지원",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/15.jpeg",
  },
  {
    title: "경상도 청년 대외활동 지원 프로그램",
    location: "경상도",
    분야: "대외활동",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/16.jpeg",
  },
  {
    title: "서울시 청년 취업 멘토링 사업",
    location: "서울특별시",
    분야: "일자리",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/17.jpeg",
  },
  {
    title: "경기도 청년 문화 축제 지원",
    location: "경기도",
    분야: "문화/예술",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/18.jpeg",
  },
  {
    title: "강원도 청년 주거비 지원",
    location: "강원도",
    분야: "주거",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/19.jpeg",
  },
  {
    title: "충청도 청년 교육 프로그램",
    location: "충청도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/20.jpeg",
  },
  {
    title: "전라도 청년 창업 지원금",
    location: "전라도",
    분야: "일자리",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/21.jpeg",
  },
  {
    title: "경상도 청년 대외활동 프로그램",
    location: "경상도",
    분야: "대외활동",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/22.jpeg",
  },
  {
    title: "서울시 청년 생활비 지원",
    location: "서울특별시",
    분야: "생활지원",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/23.jpeg",
  },
  {
    title: "경기도 청년 교육 지원",
    location: "경기도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/24.jpeg",
  },
  {
    title: "강원도 청년 취업 지원금",
    location: "강원도",
    분야: "일자리",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/25.jpeg",
  },
  {
    title: "충청도 청년 문화 행사",
    location: "충청도",
    분야: "문화/예술",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/26.jpeg",
  },
  {
    title: "전라도 청년 주거 지원",
    location: "전라도",
    분야: "주거",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/27.jpeg",
  },
  {
    title: "경상도 청년 교육 지원 사업",
    location: "경상도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/28.jpeg",
  },
  {
    title: "서울시 청년 대외활동 지원",
    location: "서울특별시",
    분야: "대외활동",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/29.jpeg",
  },
  {
    title: "경기도 청년 창업 지원 프로그램",
    location: "경기도",
    분야: "일자리",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/30.jpeg",
  },
  {
    title: "강원도 청년 생활비 지원",
    location: "강원도",
    분야: "생활지원",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/31.jpeg",
  },
  {
    title: "충청도 청년 교육 멘토링",
    location: "충청도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/32.jpeg",
  },
  {
    title: "전라도 청년 문화 지원",
    location: "전라도",
    분야: "문화/예술",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/33.jpeg",
  },
  {
    title: "경상도 청년 주거 지원 사업",
    location: "경상도",
    분야: "주거",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/34.jpeg",
  },
  {
    title: "서울시 청년 취업 지원금",
    location: "서울특별시",
    분야: "일자리",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/35.jpeg",
  },
  {
    title: "경기도 청년 창업 멘토링",
    location: "경기도",
    분야: "일자리",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/36.jpeg",
  },
  {
    title: "강원도 청년 대외활동 지원금",
    location: "강원도",
    분야: "대외활동",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/37.jpeg",
  },
  {
    title: "충청도 청년 문화 행사 지원",
    location: "충청도",
    분야: "문화/예술",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/38.jpeg",
  },
  {
    title: "전라도 청년 주거비 지원",
    location: "전라도",
    분야: "주거",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/39.jpeg",
  },
  {
    title: "경상도 청년 교육 지원금",
    location: "경상도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/40.jpeg",
  },
  {
    title: "서울시 청년 창업 지원사업",
    location: "서울특별시",
    분야: "일자리",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/41.jpeg",
  },
  {
    title: "경기도 청년 생활비 지원 프로그램",
    location: "경기도",
    분야: "생활지원",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/42.jpeg",
  },
  {
    title: "강원도 청년 문화 축제",
    location: "강원도",
    분야: "문화/예술",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/43.jpeg",
  },
  {
    title: "충청도 청년 교육 지원",
    location: "충청도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/44.jpeg",
  },
  {
    title: "전라도 청년 취업 지원금",
    location: "전라도",
    분야: "일자리",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/45.jpeg",
  },
  {
    title: "경상도 청년 대외활동 지원사업",
    location: "경상도",
    분야: "대외활동",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/46.jpeg",
  },
  {
    title: "서울시 청년 주거비 지원",
    location: "서울특별시",
    분야: "주거",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/47.jpeg",
  },
  {
    title: "경기도 청년 교육 멘토링",
    location: "경기도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/48.jpeg",
  },
  {
    title: "강원도 청년 창업 지원금",
    location: "강원도",
    분야: "일자리",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/49.jpeg",
  },
  {
    title: "충청도 청년 문화 행사 지원금",
    location: "충청도",
    분야: "문화/예술",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/50.jpeg",
  },
  {
    title: "전라도 청년 주거비 지원 프로그램",
    location: "전라도",
    분야: "주거",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/51.jpeg",
  },
  {
    title: "경상도 청년 교육 지원사업",
    location: "경상도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/52.jpeg",
  },
  {
    title: "서울시 청년 대외활동 지원사업",
    location: "서울특별시",
    분야: "대외활동",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/53.jpeg",
  },
  {
    title: "경기도 청년 창업 지원 프로그램",
    location: "경기도",
    분야: "일자리",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/54.jpeg",
  },
  {
    title: "강원도 청년 생활비 지원금",
    location: "강원도",
    분야: "생활지원",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/55.jpeg",
  },
  {
    title: "충청도 청년 교육 멘토링 프로그램",
    location: "충청도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/56.jpeg",
  },
  {
    title: "전라도 청년 문화 지원사업",
    location: "전라도",
    분야: "문화/예술",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/57.jpeg",
  },
  {
    title: "경상도 청년 주거 지원 사업",
    location: "경상도",
    분야: "주거",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/58.jpeg",
  },
  {
    title: "서울시 청년 취업 지원금",
    location: "서울특별시",
    분야: "일자리",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/59.jpeg",
  },
  {
    title: "경기도 청년 창업 멘토링 프로그램",
    location: "경기도",
    분야: "일자리",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/60.jpeg",
  },
  {
    title: "강원도 청년 대외활동 지원사업",
    location: "강원도",
    분야: "대외활동",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/61.jpeg",
  },
  {
    title: "충청도 청년 문화 행사 지원사업",
    location: "충청도",
    분야: "문화/예술",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/62.jpeg",
  },
  {
    title: "전라도 청년 주거비 지원 프로그램",
    location: "전라도",
    분야: "주거",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/63.jpeg",
  },
  {
    title: "경상도 청년 교육 지원 프로그램",
    location: "경상도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/64.jpeg",
  },
  {
    title: "서울시 청년 대외활동 지원 프로그램",
    location: "서울특별시",
    분야: "대외활동",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/65.jpeg",
  },
  {
    title: "경기도 청년 창업 지원 사업",
    location: "경기도",
    분야: "일자리",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/66.jpeg",
  },
  {
    title: "강원도 청년 생활비 지원 사업",
    location: "강원도",
    분야: "생활지원",
    취업상태: "무직",
    연령: "35~39",
    bgImage: "/img/CardImage/Policy/67.jpeg",
  },
  {
    title: "충청도 청년 교육 멘토링 사업",
    location: "충청도",
    분야: "교육",
    취업상태: "학생",
    연령: "19~24",
    bgImage: "/img/CardImage/Policy/68.jpeg",
  },
  {
    title: "전라도 청년 문화 지원 사업",
    location: "전라도",
    분야: "문화/예술",
    취업상태: "재직자",
    연령: "25~29",
    bgImage: "/img/CardImage/Policy/69.jpeg",
  },
  {
    title: "경상도 청년 주거 지원 프로그램",
    location: "경상도",
    분야: "주거",
    취업상태: "구직자",
    연령: "30~34",
    bgImage: "/img/CardImage/Policy/70.jpeg",
  },
];

export default policyDummyData;
