export const cardMeta = [
  {
    id: "card-0001",
    title: "[국립예술단체] 청년 교육단원 통합모집",
    type: "policy",
    location: ["서울특별시"],
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/1.jpeg",
  },
  {
    id: "card-0002",
    title: "자립준비청년 재보호제도",
    type: "policy",
    location: ["서울특별시", "경기도"],
    category: ["주거"],
    age: ["19~14", "25~29"],
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/2.jpeg",
  },
  {
    id: "card-0003",
    title: "문화가 있는 날",
    type: "policy",
    location: "강원도",
    category: ["문화/예술", "대외활동"],
    age: ["19~24", "25~29", "30~34", "35~39"],
    status: ["재직자", "구직자", "학생", "무직"],
    bgImage: "/img/CardImage/Policy/3.jpeg",
  },
  {
    id: "card-0004",
    title: "[중앙부처] 5분 안에 알려주는 청년정책",
    type: "policy",
    location: ["경기도", "충청도", "경상도"],
    category: ["교육", "일자리", "생활지원"],
    age: ["25~29", "30~34", "35~39"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/4.jpeg",
  },
  {
    id: "card-0005",
    title: "[서울시] 해치 콘텐츠 공모전",
    type: "policy",
    location: ["서울특별시", "경기도", "전라도"],
    category: "생활지원",
    age: ["19~24", "25~29"],
    status: ["재직자", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/5.jpeg",
  },
  {
    id: "card-0006",
    title: "2024 청년인생설계학교",
    type: "policy",
    location: ["강원도", "충청도", "경기도"],
    category: "대외활동",
    age: ["19~24", "25~29"],
    status: ["미취업", "학생"],
    bgImage: "/img/CardImage/Policy/6.jpeg",
  },
  {
    id: "card-0007",
    title: "2025 마포 청년정책 네트워크 신규위원 모집",
    type: "policy",
    location: "서울특별시",
    category: ["주거", "교육"],
    age: "30~34",
    status: ["구직자", "무직"],
    bgImage: "/img/CardImage/Policy/7.jpeg",
  },
  {
    id: "card-0008",
    title: "2025 결혼검진",
    type: "policy",
    location: "서울특별시",
    category: "주거",
    age: ["19~24", "25~29", "30~34"],
    status: ["미취업", "학생", "구직자", "무직"],
    bgImage: "/img/CardImage/Policy/8.jpeg",
  },
];
