const policyDummyData = [
  {
    id: 1,
    title: "청년 교육단원 통합 모집",
    location: "서울특별시",
    category: "일자리",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/1.jpeg",
  },
  {
    id: 2,
    title: "마포 청년정책 네트워크 신규위원 모집",
    location: "경기도",
    category: "주거",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/2.jpeg",
  },
  {
    id: 3,
    title: "2025 마포 사진 학교",
    location: "강원도",
    category: "교육",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/3.jpeg",
  },
  {
    id: 4,
    title: "서울시 청년 인생 설계 학교",
    location: "충청도",
    category: "생활지원",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/4.jpeg",
  },
  {
    id: 5,
    title: "해치 콘텐츠 공모전",
    location: "전라도",
    category: "대외활동",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/5.jpeg",
  },
  {
    id: 6,
    title: "2025 결혼검진 지원사업",
    location: "경상도",
    category: "문화/예술",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/6.jpeg",
  },
  {
    id: 7,
    title: "자립준비청년 재보호제도",
    location: "서울특별시",
    category: "일자리",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/7.jpeg",
  },
  {
    id: 8,
    title: "알고가는 중앙부처 청년정책",
    location: "경기도",
    category: "주거",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/8.jpeg",
  },
  {
    id: 9,
    title: "[CJ] 나눔 냉장고 지원사업",
    location: "강원도",
    category: "교육",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/9.jpeg",
  },
  {
    id: 10,
    title: "누구나 즐기는 문화가 있는 날",
    location: "충청도",
    category: "생활지원",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/10.jpeg",
  },

  {
    id: 11,
    title: "청년 창업 지원 프로젝트",
    location: "전라도",
    category: "대외활동",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/11.jpeg",
  },
  {
    id: 12,
    title: "청년 주거 안정 바우처",
    location: "경상도",
    category: "문화/예술",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/12.jpeg",
  },
  {
    id: 13,
    title: "직무 역량 강화 교육",
    location: "서울특별시",
    category: "일자리",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/13.jpeg",
  },
  {
    id: 14,
    title: "지역 청년 커뮤니티 활성화 지원",
    location: "경기도",
    category: "주거",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/14.jpeg",
  },
  {
    id: 15,
    title: "청년 문화 예술 창작 지원금",
    location: "강원도",
    category: "교육",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/15.jpeg",
  },
  {
    id: 16,
    title: "맞춤형 취업 컨설팅",
    location: "충청도",
    category: "생활지원",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/16.jpeg",
  },
  {
    id: 17,
    title: "청년 해외연수 프로그램",
    location: "전라도",
    category: "대외활동",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/17.jpeg",
  },
  {
    id: 18,
    title: "창업 아이디어 경진대회",
    location: "경상도",
    category: "문화/예술",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/18.jpeg",
  },
  {
    id: 19,
    title: "청년 금융 지원 사업",
    location: "서울특별시",
    category: "일자리",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/19.jpeg",
  },
  {
    id: 20,
    title: "지역사회 봉사활동 지원",
    location: "경기도",
    category: "주거",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/20.jpeg",
  },

  {
    id: 21,
    title: "청년 IT 취업 아카데미",
    location: "강원도",
    category: "교육",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/21.jpeg",
  },
  {
    id: 22,
    title: "청년 스포츠 활성화 사업",
    location: "충청도",
    category: "생활지원",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/22.jpeg",
  },
  {
    id: 23,
    title: "글로벌 청년 교류 프로그램",
    location: "전라도",
    category: "대외활동",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/23.jpeg",
  },
  {
    id: 24,
    title: "청년 문화 공간 조성 지원",
    location: "경상도",
    category: "문화/예술",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/24.jpeg",
  },
  {
    id: 25,
    title: "청년 주거 환경 개선",
    location: "서울특별시",
    category: "일자리",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/25.jpeg",
  },
  {
    id: 26,
    title: "청년 기술 창업 지원",
    location: "경기도",
    category: "주거",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/26.jpeg",
  },
  {
    id: 27,
    title: "지역 청년 네트워크 구축",
    location: "강원도",
    category: "교육",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/27.jpeg",
  },
  {
    id: 28,
    title: "청년 정책 홍보 캠페인",
    location: "충청도",
    category: "생활지원",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/28.jpeg",
  },
  {
    id: 29,
    title: "창업 지원 자금 대출",
    location: "전라도",
    category: "대외활동",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/29.jpeg",
  },
  {
    id: 30,
    title: "문화예술 교육 지원",
    location: "경상도",
    category: "문화/예술",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/30.jpeg",
  },

  {
    id: 31,
    title: "청년 해외 취업 지원",
    location: "서울특별시",
    category: "일자리",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/31.jpeg",
  },
  {
    id: 32,
    title: "청년 창업 멘토링 프로그램",
    location: "경기도",
    category: "주거",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/32.jpeg",
  },
  {
    id: 33,
    title: "직업 교육 훈련 지원",
    location: "강원도",
    category: "교육",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/33.jpeg",
  },
  {
    id: 34,
    title: "청년 예술 창작 지원",
    location: "충청도",
    category: "생활지원",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/34.jpeg",
  },
  {
    id: 35,
    title: "청년 건강 증진 프로그램",
    location: "전라도",
    category: "대외활동",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/35.jpeg",
  },
  {
    id: 36,
    title: "맞춤형 취업 알선",
    location: "경상도",
    category: "문화/예술",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/36.jpeg",
  },
  {
    id: 37,
    title: "청년 창업 지원 센터",
    location: "서울특별시",
    category: "일자리",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/37.jpeg",
  },
  {
    id: 38,
    title: "청년 주거 비용 지원",
    location: "경기도",
    category: "주거",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/38.jpeg",
  },
  {
    id: 39,
    title: "청년 문화 행사 지원",
    location: "강원도",
    category: "교육",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/39.jpeg",
  },
  {
    id: 40,
    title: "지역 청년 인재 육성",
    location: "충청도",
    category: "생활지원",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/40.jpeg",
  },

  {
    id: 41,
    title: "청년 창업가 네트워크 구축",
    location: "전라도",
    category: "대외활동",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/41.jpeg",
  },
  {
    id: 42,
    title: "청년 문화예술 창작 지원",
    location: "경상도",
    category: "문화/예술",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/42.jpeg",
  },
  {
    id: 43,
    title: "청년 IT 인재 양성",
    location: "서울특별시",
    category: "일자리",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/43.jpeg",
  },
  {
    id: 44,
    title: "청년 주거 환경 개선 사업",
    location: "경기도",
    category: "주거",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/44.jpeg",
  },
  {
    id: 45,
    title: "청년 취업 지원 컨설팅",
    location: "강원도",
    category: "교육",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/45.jpeg",
  },
  {
    id: 46,
    title: "지역 청년 문화 활성화",
    location: "충청도",
    category: "생활지원",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/46.jpeg",
  },
  {
    id: 47,
    title: "청년 창업 지원금",
    location: "전라도",
    category: "대외활동",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/47.jpeg",
  },
  {
    id: 48,
    title: "청년 문화 예술 행사",
    location: "경상도",
    category: "문화/예술",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/48.jpeg",
  },
  {
    id: 49,
    title: "청년 해외 취업 연수",
    location: "서울특별시",
    category: "일자리",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/49.jpeg",
  },
  {
    id: 50,
    title: "청년 주거 지원 정책",
    location: "경기도",
    category: "주거",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/50.jpeg",
  },

  {
    id: 51,
    title: "청년 직업 교육 프로그램",
    location: "강원도",
    category: "교육",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/51.jpeg",
  },
  {
    id: 52,
    title: "청년 문화 활동 지원",
    location: "충청도",
    category: "생활지원",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/52.jpeg",
  },
  {
    id: 53,
    title: "청년 창업 멘토링",
    location: "전라도",
    category: "대외활동",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/53.jpeg",
  },
  {
    id: 54,
    title: "청년 문화예술 창작 지원금",
    location: "경상도",
    category: "문화/예술",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/54.jpeg",
  },
  {
    id: 55,
    title: "청년 IT 취업 지원",
    location: "서울특별시",
    category: "일자리",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/55.jpeg",
  },
  {
    id: 56,
    title: "청년 주거 비용 지원 사업",
    location: "경기도",
    category: "주거",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/56.jpeg",
  },
  {
    id: 57,
    title: "청년 취업 알선 서비스",
    location: "강원도",
    category: "교육",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/57.jpeg",
  },
  {
    id: 58,
    title: "지역 청년 문화 활성화 지원",
    location: "충청도",
    category: "생활지원",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/58.jpeg",
  },
  {
    id: 59,
    title: "청년 창업 지원 센터",
    location: "전라도",
    category: "대외활동",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/59.jpeg",
  },
  {
    id: 60,
    title: "청년 문화 예술 행사 지원",
    location: "경상도",
    category: "문화/예술",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/60.jpeg",
  },

  {
    id: 61,
    title: "청년 해외 취업 지원 사업",
    location: "서울특별시",
    category: "일자리",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/61.jpeg",
  },
  {
    id: 62,
    title: "청년 주거 환경 개선 정책",
    location: "경기도",
    category: "주거",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/62.jpeg",
  },
  {
    id: 63,
    title: "청년 직업 교육 지원",
    location: "강원도",
    category: "교육",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/63.jpeg",
  },
  {
    id: 64,
    title: "청년 문화 예술 창작 지원",
    location: "충청도",
    category: "생활지원",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/64.jpeg",
  },
  {
    id: 65,
    title: "청년 건강 증진 프로그램",
    location: "전라도",
    category: "대외활동",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/65.jpeg",
  },
  {
    id: 66,
    title: "맞춤형 취업 지원",
    location: "경상도",
    category: "문화/예술",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/66.jpeg",
  },
  {
    id: 67,
    title: "청년 창업 지원금 프로그램",
    location: "서울특별시",
    category: "일자리",
    employment: "학생",
    ageRange: "30~34",
    bgImage: "/img/CardImage/Policy/67.jpeg",
  },
  {
    id: 68,
    title: "청년 주거 지원 정책",
    location: "경기도",
    category: "주거",
    employment: "무직",
    ageRange: "35~39",
    bgImage: "/img/CardImage/Policy/68.jpeg",
  },
  {
    id: 69,
    title: "청년 문화 행사 지원 사업",
    location: "강원도",
    category: "교육",
    employment: "재직자",
    ageRange: "19~24",
    bgImage: "/img/CardImage/Policy/69.jpeg",
  },
  {
    id: 70,
    title: "지역 청년 인재 육성 사업",
    location: "충청도",
    category: "생활지원",
    employment: "구직자",
    ageRange: "25~29",
    bgImage: "/img/CardImage/Policy/70.jpeg",
  },
];
